### ISSUE TITLE
不能通过编译

### ISSUE THREAD

**Issue by sguzwf** [HouQiming/jacy#2]
运行2.bat main.jc
报没有pmjs.exe,从bootstrap拷过去后报TypeError: cannot write property 'ROOT' of undefined

**Comment by HouQiming** [comment]
多谢报告！

push了一个新版本，修复了一下bootstrap的问题。加了一个生成pmjs.exe用的bootstrap.bat。

**Comment by sguzwf** [comment]
嗯，我用2008编译时报缺少stdint.h宏，加入DUK_F_NO_STDINT_H 的定义后通过编译了，谢谢！
